import ollama


def get_ai_response(model, user_text):
    """
    V2 Streaming: Yields tokens as they are generated by the model.
    """
    try:
        # stream=True is the key to ChatGPT-like speed
        stream = ollama.chat(
            model=model,
            messages=[
                {
                    'role': 'system',
                    'content': 'You are a friendly German tutor. Respond ONLY in simple German. Keep it to 1-2 sentences.'
                },
                {'role': 'user', 'content': user_text}
            ],
            stream=True
        )

        for chunk in stream:
            token = chunk['message']['content']
            yield token

    except Exception as e:
        print(f"[Ollama Error]: {e}")
        yield "Entschuldigung, ein Fehler ist aufgetreten."
